"""linking club and user again

Revision ID: 13def5cd7c0c
Revises: d50f28cea6e3
Create Date: 2021-01-12 20:06:26.461350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13def5cd7c0c'
down_revision = 'd50f28cea6e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UserToClub',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('club_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['club.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('AssocTable')
    op.drop_table('left')
    op.drop_table('right')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('right',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('right_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='right_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('left',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('left_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='left_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('AssocTable',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"AssocTable_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('left_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('right_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['left_id'], ['left.id'], name='AssocTable_left_id_fkey'),
    sa.ForeignKeyConstraint(['right_id'], ['right.id'], name='AssocTable_right_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='AssocTable_pkey')
    )
    op.drop_table('UserToClub')
    # ### end Alembic commands ###
