"""added forum and calendar

Revision ID: 1e0a7a21a942
Revises: 13def5cd7c0c
Create Date: 2021-01-12 22:06:02.509564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e0a7a21a942'
down_revision = '13def5cd7c0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendarEvent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('club', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('startTime', sa.Date(), nullable=True),
    sa.Column('endTime', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['club'], ['club.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calendarEvent_id'), 'calendarEvent', ['id'], unique=False)
    op.create_table('clubRole',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('club', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('canDeleteForum', sa.Boolean(), nullable=True),
    sa.Column('canMuteUser', sa.Boolean(), nullable=True),
    sa.Column('canBanUser', sa.Boolean(), nullable=True),
    sa.Column('canKickUser', sa.Boolean(), nullable=True),
    sa.Column('canAddEvents', sa.Boolean(), nullable=True),
    sa.Column('canAnnounce', sa.Boolean(), nullable=True),
    sa.Column('canDeleteClub', sa.Boolean(), nullable=True),
    sa.Column('canChangeImages', sa.Boolean(), nullable=True),
    sa.Column('roleRank', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['club'], ['club.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clubRole_id'), 'clubRole', ['id'], unique=False)
    op.create_table('forum',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('club', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['club'], ['club.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forum_id'), 'forum', ['id'], unique=False)
    op.create_table('clubMember',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('club', sa.Integer(), nullable=True),
    sa.Column('role', sa.Integer(), nullable=True),
    sa.Column('joined', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['club'], ['club.id'], ),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['role'], ['clubRole.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clubMember_id'), 'clubMember', ['id'], unique=False)
    op.create_table('forumFolder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('forum', sa.Integer(), nullable=True),
    sa.Column('folderName', sa.String(), nullable=True),
    sa.Column('folderOrder', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['forum'], ['forum.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forumFolder_id'), 'forumFolder', ['id'], unique=False)
    op.create_table('forumChannel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('forumFolder', sa.Integer(), nullable=True),
    sa.Column('channelName', sa.String(), nullable=True),
    sa.Column('channelOrder', sa.Integer(), nullable=True),
    sa.Column('requiredRank', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['forumFolder'], ['forumFolder.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forumChannel_id'), 'forumChannel', ['id'], unique=False)
    op.create_table('forumPost',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.Integer(), nullable=True),
    sa.Column('writer', sa.Integer(), nullable=True),
    sa.Column('timeStamp', sa.Date(), nullable=True),
    sa.Column('beenEdited', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['channel'], ['forumChannel.id'], ),
    sa.ForeignKeyConstraint(['writer'], ['clubMember.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forumPost_id'), 'forumPost', ['id'], unique=False)
    op.drop_table('UserToClub')
    op.add_column('user', sa.Column('clubs', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'club', ['clubs'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'clubs')
    op.create_table('UserToClub',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"UserToClub_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('club_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['club.id'], name='UserToClub_club_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='UserToClub_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='UserToClub_pkey')
    )
    op.drop_index(op.f('ix_forumPost_id'), table_name='forumPost')
    op.drop_table('forumPost')
    op.drop_index(op.f('ix_forumChannel_id'), table_name='forumChannel')
    op.drop_table('forumChannel')
    op.drop_index(op.f('ix_forumFolder_id'), table_name='forumFolder')
    op.drop_table('forumFolder')
    op.drop_index(op.f('ix_clubMember_id'), table_name='clubMember')
    op.drop_table('clubMember')
    op.drop_index(op.f('ix_forum_id'), table_name='forum')
    op.drop_table('forum')
    op.drop_index(op.f('ix_clubRole_id'), table_name='clubRole')
    op.drop_table('clubRole')
    op.drop_index(op.f('ix_calendarEvent_id'), table_name='calendarEvent')
    op.drop_table('calendarEvent')
    # ### end Alembic commands ###
