"""attempt 2 for demo code

Revision ID: 2a0bbf076755
Revises: cc6a2fdc9e55
Create Date: 2021-01-12 19:34:50.516329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a0bbf076755'
down_revision = 'cc6a2fdc9e55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
