"""restart alembic

Revision ID: 6c7bf36a9b24
Revises: 
Create Date: 2021-01-18 19:54:25.677189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c7bf36a9b24'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('club',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clubName', sa.String(), nullable=True),
    sa.Column('clubIcon', sa.String(), nullable=True),
    sa.Column('clubDescription', sa.String(), nullable=True),
    sa.Column('clubLat', sa.Float(), nullable=True),
    sa.Column('clubLong', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_club_id'), 'club', ['id'], unique=False)
    op.create_table('calendarEvent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('club', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('startTime', sa.Date(), nullable=True),
    sa.Column('endTime', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['club'], ['club.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calendarEvent_id'), 'calendarEvent', ['id'], unique=False)
    op.create_table('clubRole',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('club', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('canDeleteForum', sa.Boolean(), nullable=True),
    sa.Column('canMuteUser', sa.Boolean(), nullable=True),
    sa.Column('canBanUser', sa.Boolean(), nullable=True),
    sa.Column('canKickUser', sa.Boolean(), nullable=True),
    sa.Column('canAddEvents', sa.Boolean(), nullable=True),
    sa.Column('canAnnounce', sa.Boolean(), nullable=True),
    sa.Column('canDeleteClub', sa.Boolean(), nullable=True),
    sa.Column('canChangeImages', sa.Boolean(), nullable=True),
    sa.Column('roleRank', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['club'], ['club.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clubRole_id'), 'clubRole', ['id'], unique=False)
    op.create_table('forum',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('club', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['club'], ['club.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forum_id'), 'forum', ['id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('pfp_Path', sa.String(), nullable=True),
    sa.Column('clubs', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['clubs'], ['club.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_full_name'), 'user', ['full_name'], unique=False)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table('clubMember',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('club', sa.Integer(), nullable=True),
    sa.Column('role', sa.Integer(), nullable=True),
    sa.Column('joined', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['club'], ['club.id'], ),
    sa.ForeignKeyConstraint(['role'], ['clubRole.id'], ),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clubMember_id'), 'clubMember', ['id'], unique=False)
    op.create_table('forumFolder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('forum', sa.Integer(), nullable=True),
    sa.Column('folderName', sa.String(), nullable=True),
    sa.Column('folderOrder', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['forum'], ['forum.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forumFolder_id'), 'forumFolder', ['id'], unique=False)
    op.create_table('forumChannel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('forumFolder', sa.Integer(), nullable=True),
    sa.Column('channelName', sa.String(), nullable=True),
    sa.Column('channelOrder', sa.Integer(), nullable=True),
    sa.Column('requiredRank', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['forumFolder'], ['forumFolder.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forumChannel_id'), 'forumChannel', ['id'], unique=False)
    op.create_table('forumPost',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.Integer(), nullable=True),
    sa.Column('writer', sa.Integer(), nullable=True),
    sa.Column('timeStamp', sa.Date(), nullable=True),
    sa.Column('beenEdited', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['channel'], ['forumChannel.id'], ),
    sa.ForeignKeyConstraint(['writer'], ['clubMember.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forumPost_id'), 'forumPost', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_forumPost_id'), table_name='forumPost')
    op.drop_table('forumPost')
    op.drop_index(op.f('ix_forumChannel_id'), table_name='forumChannel')
    op.drop_table('forumChannel')
    op.drop_index(op.f('ix_forumFolder_id'), table_name='forumFolder')
    op.drop_table('forumFolder')
    op.drop_index(op.f('ix_clubMember_id'), table_name='clubMember')
    op.drop_table('clubMember')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_full_name'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_forum_id'), table_name='forum')
    op.drop_table('forum')
    op.drop_index(op.f('ix_clubRole_id'), table_name='clubRole')
    op.drop_table('clubRole')
    op.drop_index(op.f('ix_calendarEvent_id'), table_name='calendarEvent')
    op.drop_table('calendarEvent')
    op.drop_index(op.f('ix_club_id'), table_name='club')
    op.drop_table('club')
    # ### end Alembic commands ###
