"""another attmpet to fix the many to many

Revision ID: 827a22b856bb
Revises: a5530d19ab39
Create Date: 2021-01-11 20:05:28.703317

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '827a22b856bb'
down_revision = 'a5530d19ab39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('club',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clubName', sa.String(), nullable=True),
    sa.Column('clubIcon', sa.String(), nullable=True),
    sa.Column('clubDescription', sa.String(), nullable=True),
    sa.Column('clubLat', sa.Float(), nullable=True),
    sa.Column('clubLong', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_club_id'), 'club', ['id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('pfp_Path', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_full_name'), 'user', ['full_name'], unique=False)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.drop_index('ix_Club_id', table_name='Club')
    op.drop_table('Club')
    op.drop_index('ix_User_email', table_name='User')
    op.drop_index('ix_User_full_name', table_name='User')
    op.drop_index('ix_User_id', table_name='User')
    op.drop_table('User')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"User_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_superuser', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('pfp_Path', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='User_pkey')
    )
    op.create_index('ix_User_id', 'User', ['id'], unique=False)
    op.create_index('ix_User_full_name', 'User', ['full_name'], unique=False)
    op.create_index('ix_User_email', 'User', ['email'], unique=True)
    op.create_table('Club',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Club_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('clubName', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('clubIcon', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('clubDescription', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('clubLat', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('clubLong', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Club_pkey')
    )
    op.create_index('ix_Club_id', 'Club', ['id'], unique=False)
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_full_name'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_club_id'), table_name='club')
    op.drop_table('club')
    # ### end Alembic commands ###
