"""remove unnecessary forum model

Revision ID: 89d2904673b8
Revises: 6c7bf36a9b24
Create Date: 2021-01-18 21:37:55.528054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89d2904673b8'
down_revision = '6c7bf36a9b24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('forumFolder_forum_fkey', 'forumFolder', type_='foreignkey')
    op.drop_index('ix_forum_id', table_name='forum')
    op.drop_table('forum')
    op.add_column('forumFolder', sa.Column('club', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'forumFolder', 'club', ['club'], ['id'])
    op.drop_column('forumFolder', 'forum')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forumFolder', sa.Column('forum', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'forumFolder', type_='foreignkey')
    op.create_foreign_key('forumFolder_forum_fkey', 'forumFolder', 'forum', ['forum'], ['id'])
    op.drop_column('forumFolder', 'club')
    op.create_table('forum',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('club', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['club'], ['club.id'], name='forum_club_fkey'),
    sa.PrimaryKeyConstraint('id', name='forum_pkey')
    )
    op.create_index('ix_forum_id', 'forum', ['id'], unique=False)
    # ### end Alembic commands ###
