"""another attmpt to do demo

Revision ID: 8ef4f8eed941
Revises: e34db1db9256
Create Date: 2021-01-12 19:41:56.494520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ef4f8eed941'
down_revision = 'e34db1db9256'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
