"""attempt 2 to connect club and users

Revision ID: a5530d19ab39
Revises: 900ef7bc32f8
Create Date: 2021-01-10 00:57:35.755546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5530d19ab39'
down_revision = '900ef7bc32f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
