"""Make the pfp path in user

Revision ID: c5f927a34609
Revises: 882731b52919
Create Date: 2021-01-08 01:32:38.090506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5f927a34609'
down_revision = '882731b52919'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
