"""put demo code in

Revision ID: cc6a2fdc9e55
Revises: 827a22b856bb
Create Date: 2021-01-12 19:27:03.131272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc6a2fdc9e55'
down_revision = '827a22b856bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
