"""attempt 4

Revision ID: ef54c844fbb8
Revises: ba73b8e55ed9
Create Date: 2021-01-12 19:51:03.692926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef54c844fbb8'
down_revision = 'ba73b8e55ed9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AssocTable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('left',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('right',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('child')
    op.drop_table('parent')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parent',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('parent_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='parent_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('child',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['parent.id'], name='child_parent_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='child_pkey')
    )
    op.drop_table('right')
    op.drop_table('left')
    op.drop_table('AssocTable')
    # ### end Alembic commands ###
